production:
  clients:
    default:
      database: rtable_production
      hosts:
        - localhost:27017
      options:
        auth_source: admin
        user: <%= Rails.application.credentials.mongoid_user %>
        password: <%= Rails.application.credentials.mongoid_pass %>
        roles:
          - 'dbOwner'

staging:
  clients:
    default:
      database: rtable_staging
      hosts:
        - localhost:27017

development:
  clients:
    default:
      database: rtable_dev
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: rtable_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
